### model
model_name_or_path: /path to base model

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj, v_proj

### dataset
dataset: your_dataset
split: train
template: llama3


cutoff_len: 1024
max_samples: 5000

overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /path to output dir
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_steps: 0.1
# fp16: true

### flora
use_badam: true
badam_mode: layer
badam_switch_mode: random
badam_switch_interval: 1

### eval
val_size: 200
per_device_eval_batch_size: 1
evaluation_strategy: "steps"
eval_steps: 100
